export const channels = {
  snapshot: "data:snapshot",
  createTask: "tasks:create",
  updateTask: "tasks:update",
  completeTask: "tasks:complete",
  deleteTask: "tasks:delete",
  restoreDeletion: "tasks:restore",
  saveProject: "projects:save",
  saveTag: "tags:save",
  comments: "comments:list",
  addComment: "comments:add",
  attachments: "attachments:list",
  setPreferences: "preferences:set",
  captureAttachment: "attachments:pick",
  openAttachment: "attachments:open",
  windowAction: "window:action",
  checkUpdates: "updates:check",
  capture: "capture:requested",
  changed: "tasks:changed",
} as const;
