export const channels = {
  mailAuthStatus: "mail:authStatus",
  connectMail: "mail:connect",
  disconnectMail: "mail:disconnect",
  syncMail: "mail:sync",
  replyMail: "mail:reply",
  openMailAttachment: "mail:openAttachment",
  mailSnapshot: "mail:snapshot",
  mailAttachments: "mail:attachments",
  setMailRead: "mail:setRead",
  linkMailTask: "mail:linkTask",
  createTaskFromMail: "mail:createTask",
  waitForMailReply: "mail:waitForReply",
  resolveMailWaiting: "mail:resolveWaiting",

  notesSnapshot: "notes:notesSnapshot",
  saveNotebook: "notes:saveNotebook",
  saveSection: "notes:saveSection",
  savePage: "notes:savePage",
  deleteNote: "notes:deleteNote",
  restoreNote: "notes:restoreNote",
  linkChecklist: "notes:linkChecklist",
  searchAll: "notes:searchAll",

  snapshot: "data:snapshot",
  createTask: "tasks:create",
  updateTask: "tasks:update",
  completeTask: "tasks:complete",
  deleteTask: "tasks:delete",
  restoreDeletion: "tasks:restore",
  saveProject: "projects:save",
  saveTag: "tags:save",
  comments: "comments:list",
  addComment: "comments:add",
  attachments: "attachments:list",
  setPreferences: "preferences:set",
  captureAttachment: "attachments:pick",
  openAttachment: "attachments:open",
  windowAction: "window:action",
  checkUpdates: "updates:check",
  capture: "capture:requested",
  changed: "tasks:changed",
} as const;
